### ISSUE TITLE
VoicePackV17.act line 501

### ISSUE THREAD

**Issue by RamonaTigier** [EDDiscovery/EDDiscoveryData#21]
Static say_FSDJumpFaction $= ", System controlled by %rs(EventClass_Faction,say_ss) %ifnotempty(EventClass_FactionState,\"in state %(EventClass_FactionState)\")"

wouldn't it be better to intercept when the status is "none" and replace "none" with something meaningful?

**Comment by robbyxp1** [comment]
Yes, but it may be in other places too. 

too low priority for me to fix at the moment.

**Comment by robbyxp1** [comment]
In V18, due for 15. Thanks for the report.
