### ISSUE TITLE
VoicePackV17.act Line 426 idea

### ISSUE THREAD

**Issue by RamonaTigier** [EDDiscovery/EDDiscoveryData#23]
At the moment it says:
Static say_DockingGrantedGRN $= , when the station starboard green navigation light is on the right

What about:
Static say_DockingGrantedGRN $= , when the green beacon of the station is starboard
??

https://www.dict.cc/?s=Leuchtfeuer
or maybe beacon light!?

**Comment by robbyxp1** [comment]
In English, its called a ship navigation light, so its right.

You can change it in your packs, but its right for english.

thanks
